export {default as Info} from './info/Info'
export {default as MenuMain} from './menuMain/MenuMain'
export {default as About} from './about/About'
export {default as Feature} from './feature/Feature'
export {default as Navbar} from './navbar/Navbar'
export {default as MenuList} from './menuList/MenuList'